In [263]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
np.random.seed(0)

In [264]:
df=pd.read_csv("abalone.csv")
df
#check data has been read in properly

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [265]:
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm').set_precision(2)
##checking correlation

In [266]:
y = df["Rings"] 
df.drop('Rings', axis = 1, inplace = True)
df
##Set the target value and drop from data

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550
...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950

In [267]:
df = pd.get_dummies(df)
#### fixing dummies

In [268]:
df.drop('Sex_M', axis = 1, inplace = True)
df
x=df
###droping extra dummy variable
# Define the feature set X.

In [269]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = .30, random_state = 33)
X_train
###train and test split

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Sex_F,Sex_I
2248,0.360,0.270,0.090,0.2225,0.0830,0.0530,0.0750,0,0
1966,0.665,0.500,0.150,1.2475,0.4625,0.2955,0.3595,1,0
2760,0.550,0.430,0.145,0.7120,0.3025,0.1520,0.2250,0,1
20,0.355,0.280,0.095,0.2455,0.0955,0.0620,0.0750,0,0
838,0.480,0.365,0.135,0.6395,0.2945,0.1130,0.1750,1,0
...,...,...,...,...,...,...,...,...,...
57,0.470,0.385,0.135,0.5895,0.2765,0.1200,0.1700,0,0
3273,0.475,0.375,0.140,0.5010,0.1920,0.1175,0.1750,1,0
2706,0.725,0.530,0.190,1.7315,0.8300,0.3980,0.4050,1,0
578,0.580,0.445,0.150,0.8865,0.3830,0.2090,0.2550,0,1
2439,0.345,0.255,0.100,0.1970,0.0710,0.0510,0.0600,1,0

In [270]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler() 
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train= pd.DataFrame(X_train, columns=["Length","Diameter","Height", "Whole weight","Shucked weight","Viscera weight","Shell weight","Sex_F","Sex_I"])
X_test = pd.DataFrame(X_test, columns=["Length","Diameter","Height", "Whole weight","Shucked weight","Viscera weight","Shell weight","Sex_F","Sex_I"])
X_train
# Standardization

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Sex_F,Sex_I
0,-1.090909,-1.148148,-1.0,-0.816413,-0.791104,-0.732394,-0.821566,0.0,0.0
1,0.757576,0.555556,0.2,0.633888,0.414615,0.785603,0.639281,1.0,0.0
2,0.060606,0.037037,0.1,-0.123806,-0.093725,-0.112676,-0.051348,0.0,1.0
3,-1.121212,-1.074074,-0.9,-0.783870,-0.751390,-0.676056,-0.821566,0.0,0.0
4,-0.363636,-0.444444,-0.1,-0.226388,-0.119142,-0.356808,-0.308087,1.0,0.0
...,...,...,...,...,...,...,...,...,...
2918,-0.424242,-0.296296,-0.1,-0.297135,-0.176330,-0.312989,-0.333761,0.0,0.0
2919,-0.393939,-0.370370,0.0,-0.422356,-0.444797,-0.328638,-0.308087,1.0,0.0
2920,1.121212,0.777778,1.0,1.318712,1.582208,1.427230,0.872914,1.0,0.0
2921,0.242424,0.148148,0.2,0.123099,0.162033,0.244131,0.102696,0.0,1.0
2922,-1.181818,-1.259259,-0.8,-0.852494,-0.829230,-0.744914,-0.898588,1.0,0.0

In [273]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector as EFS
# Create lienar Regression classifier
lmodel = LinearRegression()
efs = EFS(lmodel, 
           min_features=1,
           max_features=9,
           scoring='neg_mean_squared_error',
           print_progress=True,
           cv=5)

feature_names = ("Length","Diameter","Height", "Whole weight","Shucked weight","Viscera weight","Shell weight","Sex_F","Sex_I")
efs = efs.fit(X_train, y_train, custom_feature_names=feature_names)

print('Best neg_mean_squared_error score: %.2f' % efs.best_score_)
print('Best subset (indices):', efs.best_idx_)
print('Best subset (corresponding names):', efs.best_feature_names_)

Features: 511/511

Best neg_mean_squared_error score: -4.66
Best subset (indices): (1, 3, 4, 5, 6, 8)
Best subset (corresponding names): ('Diameter', 'Whole weight', 'Shucked weight', 'Viscera weight', 'Shell weight', 'Sex_I')

In [274]:
pd.DataFrame.from_dict(efs.get_metric_dict()).T.sort_values('avg_score',ascending=False)

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
453,"(1, 3, 4, 5, 6, 8)","[-4.860503574559526, -4.528849381460856, -4.76...",-4.662365,"(Diameter, Whole weight, Shucked weight, Visce...",0.342775,0.266690,0.133345
481,"(0, 1, 3, 4, 5, 6, 8)","[-4.85984126357364, -4.533344630802083, -4.765...",-4.662844,"(Length, Diameter, Whole weight, Shucked weigh...",0.341380,0.265606,0.132803
499,"(1, 3, 4, 5, 6, 7, 8)","[-4.848967687013617, -4.524956218864693, -4.75...",-4.665105,"(Diameter, Whole weight, Shucked weight, Visce...",0.358265,0.278742,0.139371
507,"(0, 1, 3, 4, 5, 6, 7, 8)","[-4.848253419318976, -4.529578750088185, -4.75...",-4.665578,"(Length, Diameter, Whole weight, Shucked weigh...",0.356876,0.277661,0.138831
432,"(0, 3, 4, 5, 6, 8)","[-4.8980454576550985, -4.556988117378055, -4.8...",-4.700936,"(Length, Whole weight, Shucked weight, Viscera...",0.346898,0.269898,0.134949
...,...,...,...,...,...,...,...
8,"(8,)","[-7.637040855563763, -8.220391967935356, -8.62...",-7.976178,"(Sex_I,)",0.736224,0.572808,0.286404
4,"(4,)","[-7.749182131696978, -8.284733883682872, -8.92...",-8.050793,"(Shucked weight,)",0.809664,0.629946,0.314973
101,"(2, 4, 7)","[-14.647431327605103, -6.592345261578005, -6.9...",-8.071624,"(Height, Shucked weight, Sex_F)",4.254751,3.310341,1.655171
25,"(2, 4)","[-14.880391042656766, -6.595018174157331, -6.9...",-8.140503,"(Height, Shucked weight)",4.362177,3.393922,1.696961
7,"(7,)","[-8.892928173790981, -9.64768996280346, -9.775...",-9.283215,"(Sex_F,)",0.611537,0.475796,0.237898

In [275]:
X_train_selected=X_train.iloc[:,[1, 3, 4, 5, 6, 8]]
X_test_selected=X_test.iloc[:,[1, 3, 4, 5, 6, 8]]
### creating new dataset with selected features
lmodel=LinearRegression()
lmodel.fit(X_train_selected, y_train)
y_pred=lmodel.predict(X_test_selected)
mse=mean_squared_error(y_test,y_pred)
y_pred_train=lmodel.predict(X_train_selected)
mse_train=mean_squared_error(y_train,y_pred_train)
X_train_selected
print(f"test mse {mse}")
print(f"train mse {mse_train}")

test mse 5.430410659086882
train mse 4.6246535382763

In [276]:
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
lmodel=LinearRegression()
sfs = SFS(lmodel, 
           k_features=9, 
           forward=True, 
           floating=False, 
           verbose=2,
           scoring='neg_mean_squared_error',
           cv=5)
feature_names = ("Length","Diameter","Height", "Whole weight","Shucked weight","Viscera weight","Shell weight","Sex_F","Sex_I")
sfs = sfs.fit(X_train, y_train, custom_feature_names=feature_names)
sfs.subsets_

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    0.0s finished

[2021-02-03 20:00:25] Features: 1/9 -- score: -5.933428381526085[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    0.0s finished

[2021-02-03 20:00:25] Features: 2/9 -- score: -5.183333503391919[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    0.0s finished

[2021-02-03 20:00:25] Features: 3/9 -- score: -4.9109847432422615[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    0.0s finished

[2021-02-03 20:00:25] Features: 4/9 -- score: -4.789151324650938[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished

[2021-02-03 20:00:25] Features: 5/9 -- score: -4.712976782483757[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s finished

[2021-02-03 20:00:25] Features: 6/9 -- score: -4.662364860607587[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s finished

[2021-02-03 20:00:25] Features: 7/9 -- score: -4.662843687269982[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s finished

[2021-02-03 20:00:25] Features: 8/9 -- score: -4.665578237159392[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

[2021-02-03 20:00:25] Features: 9/9 -- score: -4.797528906357049

{1: {'feature_idx': (6,),
  'cv_scores': array([-5.920509  , -6.01489284, -6.39854641, -5.38244045, -5.95075321]),
  'avg_score': -5.933428381526085,
  'feature_names': ('Shell weight',)},
 2: {'feature_idx': (4, 6),
  'cv_scores': array([-5.33369009, -5.01311199, -5.13629261, -4.96442498, -5.46914784]),
  'avg_score': -5.183333503391919,
  'feature_names': ('Shucked weight', 'Shell weight')},
 3: {'feature_idx': (1, 4, 6),
  'cv_scores': array([-5.16269075, -4.74936849, -4.92545657, -4.58291533, -5.13449258]),
  'avg_score': -4.9109847432422615,
  'feature_names': ('Diameter', 'Shucked weight', 'Shell weight')},
 4: {'feature_idx': (1, 4, 6, 8),
  'cv_scores': array([-5.034723  , -4.65134784, -4.80474598, -4.43199961, -5.02294019]),
  'avg_score': -4.789151324650938,
  'feature_names': ('Diameter', 'Shucked weight', 'Shell weight', 'Sex_I')},
 5: {'feature_idx': (1, 3, 4, 6, 8),
  'cv_scores': array([-4.93564374, -4.65039215, -4.71962224, -4.27326268, -4.9859631 ]),
  'avg_score': -4.712976782483757,
  'feature_names': ('Diameter',
   'Whole weight',
   'Shucked weight',
   'Shell weight',
   'Sex_I')},
 6: {'feature_idx': (1, 3, 4, 5, 6, 8),
  'cv_scores': array([-4.86050357, -4.52884938, -4.76702878, -4.20809329, -4.94734928]),
  'avg_score': -4.662364860607587,
  'feature_names': ('Diameter',
   'Whole weight',
   'Shucked weight',
   'Viscera weight',
   'Shell weight',
   'Sex_I')},
 7: {'feature_idx': (0, 1, 3, 4, 5, 6, 8),
  'cv_scores': array([-4.85984126, -4.53334463, -4.76598   , -4.20877278, -4.94627976]),
  'avg_score': -4.662843687269982,
  'feature_names': ('Length',
   'Diameter',
   'Whole weight',
   'Shucked weight',
   'Viscera weight',
   'Shell weight',
   'Sex_I')},
 8: {'feature_idx': (0, 1, 3, 4, 5, 6, 7, 8),
  'cv_scores': array([-4.84825342, -4.52957875, -4.75751584, -4.19906012, -4.99348306]),
  'avg_score': -4.665578237159392,
  'feature_names': ('Length',
   'Diameter',
   'Whole weight',
   'Shucked weight',
   'Viscera weight',
   'Shell weight',
   'Sex_F',
   'Sex_I')},
 9: {'feature_idx': (0, 1, 2, 3, 4, 5, 6, 7, 8),
  'cv_scores': array([-5.82964963, -4.47584387, -4.66331302, -4.13652703, -4.88231098]),
  'avg_score': -4.797528906357049,
  'feature_names': ('Length',
   'Diameter',
   'Height',
   'Whole weight',
   'Shucked weight',
   'Viscera weight',
   'Shell weight',
   'Sex_F',
   'Sex_I')}}

In [277]:
pd.DataFrame.from_dict(sfs.get_metric_dict()).T.sort_values('avg_score',ascending=False)
##we have the same result as previous one so we will have the same result

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
6,"(1, 3, 4, 5, 6, 8)","[-4.860503574559526, -4.528849381460856, -4.76...",-4.662365,"(Diameter, Whole weight, Shucked weight, Visce...",0.342775,0.266690,0.133345
7,"(0, 1, 3, 4, 5, 6, 8)","[-4.85984126357364, -4.533344630802083, -4.765...",-4.662844,"(Length, Diameter, Whole weight, Shucked weigh...",0.341380,0.265606,0.132803
8,"(0, 1, 3, 4, 5, 6, 7, 8)","[-4.848253419318976, -4.529578750088185, -4.75...",-4.665578,"(Length, Diameter, Whole weight, Shucked weigh...",0.356876,0.277661,0.138831
5,"(1, 3, 4, 6, 8)","[-4.93564373839955, -4.650392147440645, -4.719...",-4.712977,"(Diameter, Whole weight, Shucked weight, Shell...",0.325872,0.253540,0.126770
4,"(1, 4, 6, 8)","[-5.034722998683491, -4.651347842682321, -4.80...",-4.789151,"(Diameter, Shucked weight, Shell weight, Sex_I)",0.294078,0.228803,0.114401
9,"(0, 1, 2, 3, 4, 5, 6, 7, 8)","[-5.829649629707367, -4.475843869987672, -4.66...",-4.797529,"(Length, Diameter, Height, Whole weight, Shuck...",0.734053,0.571118,0.285559
3,"(1, 4, 6)","[-5.162690752227443, -4.749368488929792, -4.92...",-4.910985,"(Diameter, Shucked weight, Shell weight)",0.285827,0.222383,0.111191
2,"(4, 6)","[-5.333690088226049, -5.013111993225855, -5.13...",-5.183334,"(Shucked weight, Shell weight)",0.246163,0.191523,0.095762
1,"(6,)","[-5.920508997029952, -6.014892837676718, -6.39...",-5.933428,"(Shell weight,)",0.417285,0.324662,0.162331

In [304]:
X_train_selected=X_train.iloc[:,[1, 3, 4, 5, 6, 8]]
X_test_selected=X_test.iloc[:,[1, 3, 4, 5, 6, 8]]
### creating new dataset with selected features
lmodel=LinearRegression()
lmodel.fit(X_train_selected, y_train)
y_pred=lmodel.predict(X_test_selected)
mse=mean_squared_error(y_test,y_pred)
y_pred_train=lmodel.predict(X_train_selected)
mse_train=mean_squared_error(y_train,y_pred_train)
X_train_selected
print(f"test mse {mse}")
print(f"train mse {mse_train}")

test mse 5.430410659086882
train mse 4.6246535382763

In [305]:
##backward selection
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
lmodel=LinearRegression()
sbs = SFS(lmodel, 
           k_features=1, 
           forward=False, 
           floating=False, 
           verbose=2,
           scoring='neg_mean_squared_error',
           cv=5
           )
feature_names = ("Length","Diameter","Height", "Whole weight","Shucked weight","Viscera weight","Shell weight","Sex_F","Sex_I")
sbs = sbs.fit(X_train, y_train, custom_feature_names=feature_names)
sbs.subsets_

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    0.0s finished

[2021-02-03 22:40:00] Features: 8/1 -- score: -4.665578237159392[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    0.0s finished

[2021-02-03 22:40:00] Features: 7/1 -- score: -4.662843687269982[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    0.0s finished

[2021-02-03 22:40:00] Features: 6/1 -- score: -4.662364860607587[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    0.0s finished

[2021-02-03 22:40:00] Features: 5/1 -- score: -4.712976782483757[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished

[2021-02-03 22:40:00] Features: 4/1 -- score: -4.789151324650937[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s finished

[2021-02-03 22:40:00] Features: 3/1 -- score: -4.9109847432422615[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s finished

[2021-02-03 22:40:00] Features: 2/1 -- score: -5.183333503391919[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s finished

[2021-02-03 22:40:01] Features: 1/1 -- score: -5.933428381526085

{9: {'feature_idx': (0, 1, 2, 3, 4, 5, 6, 7, 8),
  'cv_scores': array([-5.82964963, -4.47584387, -4.66331302, -4.13652703, -4.88231098]),
  'avg_score': -4.797528906357049,
  'feature_names': ('Length',
   'Diameter',
   'Height',
   'Whole weight',
   'Shucked weight',
   'Viscera weight',
   'Shell weight',
   'Sex_F',
   'Sex_I')},
 8: {'feature_idx': (0, 1, 3, 4, 5, 6, 7, 8),
  'cv_scores': array([-4.84825342, -4.52957875, -4.75751584, -4.19906012, -4.99348306]),
  'avg_score': -4.665578237159392,
  'feature_names': ('Length',
   'Diameter',
   'Whole weight',
   'Shucked weight',
   'Viscera weight',
   'Shell weight',
   'Sex_F',
   'Sex_I')},
 7: {'feature_idx': (0, 1, 3, 4, 5, 6, 8),
  'cv_scores': array([-4.85984126, -4.53334463, -4.76598   , -4.20877278, -4.94627976]),
  'avg_score': -4.662843687269982,
  'feature_names': ('Length',
   'Diameter',
   'Whole weight',
   'Shucked weight',
   'Viscera weight',
   'Shell weight',
   'Sex_I')},
 6: {'feature_idx': (1, 3, 4, 5, 6, 8),
  'cv_scores': array([-4.86050357, -4.52884938, -4.76702878, -4.20809329, -4.94734928]),
  'avg_score': -4.662364860607587,
  'feature_names': ('Diameter',
   'Whole weight',
   'Shucked weight',
   'Viscera weight',
   'Shell weight',
   'Sex_I')},
 5: {'feature_idx': (1, 3, 4, 6, 8),
  'cv_scores': array([-4.93564374, -4.65039215, -4.71962224, -4.27326268, -4.9859631 ]),
  'avg_score': -4.712976782483757,
  'feature_names': ('Diameter',
   'Whole weight',
   'Shucked weight',
   'Shell weight',
   'Sex_I')},
 4: {'feature_idx': (1, 4, 6, 8),
  'cv_scores': array([-5.034723  , -4.65134784, -4.80474598, -4.43199961, -5.02294019]),
  'avg_score': -4.789151324650937,
  'feature_names': ('Diameter', 'Shucked weight', 'Shell weight', 'Sex_I')},
 3: {'feature_idx': (1, 4, 6),
  'cv_scores': array([-5.16269075, -4.74936849, -4.92545657, -4.58291533, -5.13449258]),
  'avg_score': -4.9109847432422615,
  'feature_names': ('Diameter', 'Shucked weight', 'Shell weight')},
 2: {'feature_idx': (4, 6),
  'cv_scores': array([-5.33369009, -5.01311199, -5.13629261, -4.96442498, -5.46914784]),
  'avg_score': -5.183333503391919,
  'feature_names': ('Shucked weight', 'Shell weight')},
 1: {'feature_idx': (6,),
  'cv_scores': array([-5.920509  , -6.01489284, -6.39854641, -5.38244045, -5.95075321]),
  'avg_score': -5.933428381526085,
  'feature_names': ('Shell weight',)}}

In [279]:
pd.DataFrame.from_dict(sbs.get_metric_dict()).T.sort_values('avg_score',ascending=False)
##backward and all forward techniques gave the same column set

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
6,"(1, 3, 4, 5, 6, 8)","[-4.860503574559526, -4.528849381460856, -4.76...",-4.662365,"(Diameter, Whole weight, Shucked weight, Visce...",0.342775,0.266690,0.133345
7,"(0, 1, 3, 4, 5, 6, 8)","[-4.85984126357364, -4.533344630802083, -4.765...",-4.662844,"(Length, Diameter, Whole weight, Shucked weigh...",0.341380,0.265606,0.132803
8,"(0, 1, 3, 4, 5, 6, 7, 8)","[-4.848253419318976, -4.529578750088185, -4.75...",-4.665578,"(Length, Diameter, Whole weight, Shucked weigh...",0.356876,0.277661,0.138831
5,"(1, 3, 4, 6, 8)","[-4.93564373839955, -4.650392147440645, -4.719...",-4.712977,"(Diameter, Whole weight, Shucked weight, Shell...",0.325872,0.253540,0.126770
4,"(1, 4, 6, 8)","[-5.034722998683491, -4.651347842682322, -4.80...",-4.789151,"(Diameter, Shucked weight, Shell weight, Sex_I)",0.294078,0.228803,0.114401
9,"(0, 1, 2, 3, 4, 5, 6, 7, 8)","[-5.829649629707367, -4.475843869987672, -4.66...",-4.797529,"(Length, Diameter, Height, Whole weight, Shuck...",0.734053,0.571118,0.285559
3,"(1, 4, 6)","[-5.162690752227443, -4.749368488929792, -4.92...",-4.910985,"(Diameter, Shucked weight, Shell weight)",0.285827,0.222383,0.111191
2,"(4, 6)","[-5.333690088226049, -5.013111993225855, -5.13...",-5.183334,"(Shucked weight, Shell weight)",0.246163,0.191523,0.095762
1,"(6,)","[-5.920508997029952, -6.014892837676718, -6.39...",-5.933428,"(Shell weight,)",0.417285,0.324662,0.162331

In [308]:
X_train_selected=X_train.iloc[:,[1, 3, 4, 5, 6, 8]]
X_test_selected=X_test.iloc[:,[1, 3, 4, 5, 6, 8]]

lmodel=LinearRegression()
lmodel.fit(X_train_selected, y_train)
y_pred=lmodel.predict(X_test_selected)
mse=mean_squared_error(y_test,y_pred)
y_pred_train=lmodel.predict(X_train_selected)
mse_train=mean_squared_error(y_train,y_pred_train)
X_train_selected
print(f"test mse {mse}")
print(f"train mse {mse_train}")

test mse 5.430410659086882
train mse 4.6246535382763

In [281]:
from sklearn.linear_model import Ridge, RidgeCV, Lasso, LassoCV
###

In [282]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
lambdas = np.logspace(-4,-0.5,60)
scoresCV = []
for l in lambdas:
    RidgeReg = Ridge(alpha=l)
    RidgeReg.fit(X_train, y_train)    
    scoreCV = cross_val_score(RidgeReg, X_train, y_train, scoring='neg_mean_squared_error',
                             cv=KFold(n_splits=10, shuffle=True,
                                            random_state=1))
    scoresCV.append([l,-1*np.mean(scoreCV)])
df = pd.DataFrame(scoresCV,columns=['Lambda','Validation Error'])
df

      Lambda  Validation Error
0   0.000100          4.821343
1   0.000115          4.821343
2   0.000131          4.821343
3   0.000151          4.821343
4   0.000173          4.821343
5   0.000198          4.821343
6   0.000227          4.821343
7   0.000260          4.821343
8   0.000298          4.821343
9   0.000342          4.821343
10  0.000392          4.821343
11  0.000449          4.821343
12  0.000515          4.821342
13  0.000590          4.821342
14  0.000677          4.821342
15  0.000776          4.821342
16  0.000890          4.821342
17  0.001020          4.821342
18  0.001169          4.821341
19  0.001340          4.821341
20  0.001536          4.821341
21  0.001761          4.821340
22  0.002019          4.821340
23  0.002314          4.821339
24  0.002653          4.821338
25  0.003041          4.821338
26  0.003486          4.821337
27  0.003997          4.821336
28  0.004582          4.821335
29  0.005252          4.821334
30  0.006021          4.821332
31  0.006902          4.821330
32  0.007912          4.821329
33  0.009070          4.821326
34  0.010398          4.821324
35  0.011920          4.821321
36  0.013664          4.821318
37  0.015664          4.821314
38  0.017957          4.821310
39  0.020585          4.821305
40  0.023598          4.821300
41  0.027052          4.821294
42  0.031012          4.821287
43  0.035551          4.821279
44  0.040754          4.821270
45  0.046719          4.821260
46  0.053557          4.821249
47  0.061395          4.821237
48  0.070381          4.821223
49  0.080683          4.821207
50  0.092491          4.821190
51  0.106029          4.821172
52  0.121547          4.821151
53  0.139337          4.821129
54  0.159731          4.821106
55  0.183110          4.821082
56  0.209910          4.821058
57  0.240633          4.821035
58  0.275853          4.821013
59  0.316228          4.820995

In [284]:
df.sort_values(by=['Validation Error'])

      Lambda  Validation Error
59  0.316228          4.820995
58  0.275853          4.821013
57  0.240633          4.821035
56  0.209910          4.821058
55  0.183110          4.821082
54  0.159731          4.821106
53  0.139337          4.821129
52  0.121547          4.821151
51  0.106029          4.821172
50  0.092491          4.821190
49  0.080683          4.821207
48  0.070381          4.821223
47  0.061395          4.821237
46  0.053557          4.821249
45  0.046719          4.821260
44  0.040754          4.821270
43  0.035551          4.821279
42  0.031012          4.821287
41  0.027052          4.821294
40  0.023598          4.821300
39  0.020585          4.821305
38  0.017957          4.821310
37  0.015664          4.821314
36  0.013664          4.821318
35  0.011920          4.821321
34  0.010398          4.821324
33  0.009070          4.821326
32  0.007912          4.821329
31  0.006902          4.821330
30  0.006021          4.821332
29  0.005252          4.821334
28  0.004582          4.821335
27  0.003997          4.821336
26  0.003486          4.821337
25  0.003041          4.821338
24  0.002653          4.821338
23  0.002314          4.821339
22  0.002019          4.821340
21  0.001761          4.821340
20  0.001536          4.821341
19  0.001340          4.821341
18  0.001169          4.821341
17  0.001020          4.821342
16  0.000890          4.821342
15  0.000776          4.821342
14  0.000677          4.821342
13  0.000590          4.821342
12  0.000515          4.821342
11  0.000449          4.821343
10  0.000392          4.821343
9   0.000342          4.821343
8   0.000298          4.821343
7   0.000260          4.821343
6   0.000227          4.821343
5   0.000198          4.821343
4   0.000173          4.821343
3   0.000151          4.821343
2   0.000131          4.821343
1   0.000115          4.821343
0   0.000100          4.821343

In [285]:
ridge = Ridge(alpha = 0.316228)
ridge.fit(X_train, y_train)     # Fit a ridge regression on the training data        
pred = ridge.predict(X_test)           # Use this model to predict the test data 
print(pd.Series(ridge.coef_, index = x.columns)) # Print coefficients
print(mean_squared_error(y_test, pred))   # Calculate the test MSE

Length           -0.250842
Diameter          1.642411
Height            0.490801
Whole weight      5.396456
Shucked weight   -5.768758
Viscera weight   -1.450057
Shell weight      1.997923
Sex_F            -0.170323
Sex_I            -0.897887
dtype: float64
5.393122628466965

In [286]:
alphas = np.logspace(-4,-0.5,60)
ridgecv = RidgeCV(alphas = alphas,cv = 10, scoring = 'neg_mean_squared_error')
ridgecv.fit(X_train, y_train)
ridgecv.alpha_

0.0001

In [287]:
ridge = Ridge(alpha = ridgecv.alpha_)
ridge.fit(X_train, y_train)             
pred = ridge.predict(X_test)  
trainpred= ridge.predict(X_train)
print(pd.Series(ridge.coef_, index = x.columns)) 
print(f"mse {mean_squared_error(y_test, pred)}")   
print(f"train mse {mean_squared_error(y_train, trainpred)}")

Length           -0.260551
Diameter          1.654374
Height            0.489724
Whole weight      5.583376
Shucked weight   -5.855789
Viscera weight   -1.494181
Shell weight      1.938194
Sex_F            -0.171340
Sex_I            -0.897242
dtype: float64
mse 5.3887779434437215
train mse 4.565852132221173

In [288]:
lambdas = np.logspace(-4,-0.5,60)
scoresCV = []
for l in lambdas:
    lassoReg = Lasso(alpha=l,max_iter=10000)
    lassoReg.fit(X_train, y_train)    
    scoreCV = cross_val_score(lassoReg, X_train, y_train, scoring='neg_mean_squared_error',
                             cv=KFold(n_splits=10, shuffle=True,
                                            random_state=1))
    scoresCV.append([l,-1*np.mean(scoreCV)])
df = pd.DataFrame(scoresCV,columns=['Lambda','Validation Error'])
df

      Lambda  Validation Error
0   0.000100          4.821052
1   0.000115          4.821006
2   0.000131          4.820953
3   0.000151          4.820893
4   0.000173          4.820825
5   0.000198          4.820748
6   0.000227          4.820661
7   0.000260          4.820562
8   0.000298          4.820451
9   0.000342          4.820327
10  0.000392          4.820187
11  0.000449          4.820032
12  0.000515          4.819859
13  0.000590          4.819669
14  0.000677          4.819461
15  0.000776          4.819236
16  0.000890          4.818995
17  0.001020          4.818742
18  0.001169          4.818458
19  0.001340          4.818154
20  0.001536          4.817818
21  0.001761          4.817431
22  0.002019          4.817050
23  0.002314          4.816709
24  0.002653          4.816527
25  0.003041          4.816562
26  0.003486          4.816809
27  0.003997          4.818172
28  0.004582          4.820389
29  0.005252          4.823781
30  0.006021          4.828225
31  0.006902          4.834052
32  0.007912          4.841691
33  0.009070          4.851712
34  0.010398          4.864670
35  0.011920          4.881433
36  0.013664          4.901136
37  0.015664          4.921355
38  0.017957          4.938730
39  0.020585          4.952541
40  0.023598          4.962335
41  0.027052          4.971427
42  0.031012          4.983778
43  0.035551          5.000287
44  0.040754          5.021887
45  0.046719          5.050055
46  0.053557          5.086770
47  0.061395          5.134736
48  0.070381          5.197276
49  0.080683          5.279051
50  0.092491          5.373741
51  0.106029          5.489549
52  0.121547          5.644776
53  0.139337          5.828262
54  0.159731          6.052351
55  0.183110          6.094293
56  0.209910          6.115944
57  0.240633          6.142583
58  0.275853          6.177857
59  0.316228          6.224520

In [289]:
df.sort_values(by=['Validation Error'])

      Lambda  Validation Error
24  0.002653          4.816527
25  0.003041          4.816562
23  0.002314          4.816709
26  0.003486          4.816809
22  0.002019          4.817050
21  0.001761          4.817431
20  0.001536          4.817818
19  0.001340          4.818154
27  0.003997          4.818172
18  0.001169          4.818458
17  0.001020          4.818742
16  0.000890          4.818995
15  0.000776          4.819236
14  0.000677          4.819461
13  0.000590          4.819669
12  0.000515          4.819859
11  0.000449          4.820032
10  0.000392          4.820187
9   0.000342          4.820327
28  0.004582          4.820389
8   0.000298          4.820451
7   0.000260          4.820562
6   0.000227          4.820661
5   0.000198          4.820748
4   0.000173          4.820825
3   0.000151          4.820893
2   0.000131          4.820953
1   0.000115          4.821006
0   0.000100          4.821052
29  0.005252          4.823781
30  0.006021          4.828225
31  0.006902          4.834052
32  0.007912          4.841691
33  0.009070          4.851712
34  0.010398          4.864670
35  0.011920          4.881433
36  0.013664          4.901136
37  0.015664          4.921355
38  0.017957          4.938730
39  0.020585          4.952541
40  0.023598          4.962335
41  0.027052          4.971427
42  0.031012          4.983778
43  0.035551          5.000287
44  0.040754          5.021887
45  0.046719          5.050055
46  0.053557          5.086770
47  0.061395          5.134736
48  0.070381          5.197276
49  0.080683          5.279051
50  0.092491          5.373741
51  0.106029          5.489549
52  0.121547          5.644776
53  0.139337          5.828262
54  0.159731          6.052351
55  0.183110          6.094293
56  0.209910          6.115944
57  0.240633          6.142583
58  0.275853          6.177857
59  0.316228          6.224520

In [295]:
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
lasso = Lasso(random_state=33, max_iter=10000)
alphas =  np.logspace(-4, -0.5, 30)
tuned_parameters = [{'alpha': alphas}]
n_folds = 10

clf = GridSearchCV(lasso, tuned_parameters, cv=n_folds, scoring='neg_mean_squared_error',refit=True)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
y_train_pred = clf.predict(X_train)
train_mse = mean_squared_error(y_train, y_train_pred)

mse = mean_squared_error(y_test,y_pred)
print("Lasso MSE: ",mse)
print("Lasso Train MSE: ",train_mse)

Lasso MSE:  5.408385075666127
Lasso Train MSE:  4.570465663893912

In [296]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
lambdas = np.logspace(-4, -0.5, 30)
scoresCV = []
for l in lambdas:
    lassoReg = Lasso(alpha=l,max_iter=10000)
    lassoReg.fit(X_train, y_train)    
    scoreCV = cross_val_score(lassoReg, X_train, y_train, scoring='neg_mean_squared_error',
                             cv=KFold(n_splits=10, shuffle=True,
                                            random_state=1))
    scoresCV.append([l,-1*np.mean(scoreCV)])
df = pd.DataFrame(scoresCV,columns=['Lambda','Validation Error'])
df

      Lambda  Validation Error
0   0.000100          4.821052
1   0.000132          4.820951
2   0.000174          4.820820
3   0.000230          4.820651
4   0.000304          4.820435
5   0.000401          4.820162
6   0.000530          4.819821
7   0.000700          4.819408
8   0.000924          4.818926
9   0.001220          4.818362
10  0.001610          4.817684
11  0.002126          4.816914
12  0.002807          4.816521
13  0.003707          4.817336
14  0.004894          4.821912
15  0.006462          4.831042
16  0.008532          4.846883
17  0.011265          4.873956
18  0.014874          4.913893
19  0.019638          4.947902
20  0.025929          4.968337
21  0.034236          4.995311
22  0.045204          5.042572
23  0.059685          5.123704
24  0.078805          5.263367
25  0.104050          5.471441
26  0.137382          5.807678
27  0.181393          6.092371
28  0.239503          6.141534
29  0.316228          6.224520

In [297]:
df.sort_values(by=['Validation Error'])

      Lambda  Validation Error
12  0.002807          4.816521
11  0.002126          4.816914
13  0.003707          4.817336
10  0.001610          4.817684
9   0.001220          4.818362
8   0.000924          4.818926
7   0.000700          4.819408
6   0.000530          4.819821
5   0.000401          4.820162
4   0.000304          4.820435
3   0.000230          4.820651
2   0.000174          4.820820
1   0.000132          4.820951
0   0.000100          4.821052
14  0.004894          4.821912
15  0.006462          4.831042
16  0.008532          4.846883
17  0.011265          4.873956
18  0.014874          4.913893
19  0.019638          4.947902
20  0.025929          4.968337
21  0.034236          4.995311
22  0.045204          5.042572
23  0.059685          5.123704
24  0.078805          5.263367
25  0.104050          5.471441
26  0.137382          5.807678
27  0.181393          6.092371
28  0.239503          6.141534
29  0.316228          6.224520

In [298]:
lassocv = LassoCV(alphas = None, cv = 10, max_iter = 100000)
lassocv.fit(X_train, y_train) # Fit a Lasso regression on the training data
lasso.set_params(alpha=lassocv.alpha_) # Use this model to predict the test data


train_mse = mean_squared_error(y_train,lasso.predict(X_train))

mse=mean_squared_error(y_test, lasso.predict(X_test))
print("Lasso MSE: ",mse)        # Calculate the test MSE
print("Lasso Train MSE: ",train_mse)

Lasso MSE:  5.4058378447622575
Lasso Train MSE:  4.56976267329224

In [299]:
lassocv.alpha_

0.002535222981726945

In [300]:
pd.Series(lasso.coef_, index=x.columns)  # Print coefficients

Length           -0.000000
Diameter          1.385563
Height            0.488295
Whole weight      4.816910
Shucked weight   -5.519448
Viscera weight   -1.267617
Shell weight      2.168515
Sex_F            -0.146551
Sex_I            -0.882915
dtype: float64

In [303]:
lr = LinearRegression()
lr.fit(X_train,y_train)            
y_pred = lr.predict(X_test)        
y_train_pred = lr.predict(X_train)
mse = mean_squared_error(y_test, y_pred)
train_mse = mean_squared_error(y_train, y_train_pred)
print("Mean Squared Error :", mse)
print("Train MSE: ", train_mse) 
pd.Series(lr.coef_, index=x.columns)

Mean Squared Error : 5.388776577744681
Train MSE:  4.565852132204131

Length           -0.260554
Diameter          1.654378
Height            0.489724
Whole weight      5.583438
Shucked weight   -5.855818
Viscera weight   -1.494195
Shell weight      1.938175
Sex_F            -0.171340
Sex_I            -0.897241
dtype: float64